codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 65..100
  round: down
  precision: 2
  status:
    project:
      default:
        # basic
        target: 68

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: yes  # if true: only post the comment if coverage changes
