version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: NginxDockerfile
    container_name: nginx
    depends_on:
      - prometheus
    ports:
      - 9000:80

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - message_producer
      - naz_cli
      - push_to_gateway
      - timescale_db

  push_to_gateway:
    image: prom/pushgateway
    container_name: push_to_gateway

  message_producer:
    build:
      context: .
    container_name: message_producer
    volumes:
      - ./:/usr/src/app
    command: python /usr/src/app/message_producer.py
    env_file:
      - compose.env
    labels:
      - "app_name=message_producer"

  naz_cli:
    build:
      context: .
    container_name: naz_cli
    volumes:
      - ./:/usr/src/app
    command: naz-cli --client app.my_naz_client
    env_file:
      - compose.env
    labels:
      - "app_name=naz_cli"
    depends_on:
      - timescale_db

  # for log storage
  timescale_db:
    container_name: timescale_db
    build:
      context: .
      dockerfile: timescale_dockerfile
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: hey_NSA
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - ./:/usr/src/app
