scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: push_to_gateway
  honor_labels: true
  scrape_interval: 5s
  static_configs:
  - targets:
    - push_to_gateway:9091